/* ==================================================================== *
 *  Villes par pays (CEDEAO) — à la place du texte libre
 *
 *  Liste des villes/communes majeures, pas un gazetteer exhaustif.
 *  Traitement approfondi pour la Côte d'Ivoire (marché principal de
 *  l'app) : les communes d'Abidjan sont listées individuellement, un
 *  vendeur y trouve un repère plus précis qu'"Abidjan" seul.
 * ==================================================================== */

export const CITIES: Record<string, string[]> = {
  CI: [
    "Abidjan — Cocody",
    "Abidjan — Yopougon",
    "Abidjan — Marcory",
    "Abidjan — Treichville",
    "Abidjan — Koumassi",
    "Abidjan — Plateau",
    "Abidjan — Adjamé",
    "Abidjan — Abobo",
    "Abidjan — Attécoubé",
    "Abidjan — Port-Bouët",
    "Abidjan — Bingerville",
    "Abidjan — Anyama",
    "Bouaké",
    "Yamoussoukro",
    "San-Pédro",
    "Korhogo",
    "Daloa",
    "Man",
    "Gagnoa",
    "Abengourou",
    "Bondoukou",
    "Divo",
    "Agboville",
    "Grand-Bassam",
    "Séguéla",
    "Odienné",
    "Ferkessédougou",
    "Soubré",
    "Dabou",
    "Bouaflé",
  ],
  BJ: [
    "Cotonou",
    "Porto-Novo",
    "Parakou",
    "Abomey-Calavi",
    "Djougou",
    "Bohicon",
    "Kandi",
    "Lokossa",
    "Ouidah",
    "Abomey",
    "Natitingou",
    "Savalou",
  ],
  BF: [
    "Ouagadougou",
    "Bobo-Dioulasso",
    "Koudougou",
    "Banfora",
    "Ouahigouya",
    "Kaya",
    "Tenkodogo",
    "Fada N'Gourma",
    "Dédougou",
    "Gaoua",
  ],
  CV: ["Praia", "Mindelo", "Santa Maria", "Assomada", "Espargos", "Pedra Badejo"],
  GM: ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni", "Lamin"],
  GH: [
    "Accra",
    "Kumasi",
    "Tamale",
    "Sekondi-Takoradi",
    "Ashaiman",
    "Sunyani",
    "Cape Coast",
    "Obuasi",
    "Tema",
    "Koforidua",
  ],
  GN: ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Labé", "Mamou", "Boké", "Faranah", "Kissidougou"],
  GW: ["Bissau", "Bafatá", "Gabú", "Bissorã", "Canchungo"],
  LR: ["Monrovia", "Gbarnga", "Buchanan", "Kakata", "Voinjama", "Zwedru", "Harper"],
  ML: ["Bamako", "Sikasso", "Mopti", "Koutiala", "Ségou", "Kayes", "Gao", "Kati", "Tombouctou"],
  NE: ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua", "Dosso", "Arlit"],
  NG: [
    "Lagos",
    "Abuja",
    "Kano",
    "Ibadan",
    "Port Harcourt",
    "Benin City",
    "Kaduna",
    "Enugu",
    "Onitsha",
    "Warri",
  ],
  SN: [
    "Dakar",
    "Touba",
    "Thiès",
    "Rufisque",
    "Kaolack",
    "Ziguinchor",
    "Saint-Louis",
    "Mbour",
    "Diourbel",
    "Louga",
  ],
  SL: ["Freetown", "Bo", "Kenema", "Makeni", "Koidu", "Waterloo"],
  TG: ["Lomé", "Sokodé", "Kara", "Kpalimé", "Atakpamé", "Dapaong", "Tsévié"],
};

export const citiesFor = (iso: string): string[] => CITIES[iso] ?? [];
